image: docker:stable

variables:
  LATEST_VER: $CI_REGISTRY_IMAGE:latest
  MAJOR_VER: $CI_REGISTRY_IMAGE:1.2.0

stages:
  - build

build:
  stage: build
  only:
  - master
  services:
   - docker:19.03.1-dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $LATEST_VER
    - docker tag $LATEST_VER $MAJOR_VER
    - docker push $LATEST_VER && docker image rm $LATEST_VER
    - docker push $MAJOR_VER && docker image rm $MAJOR_VER
